// Maps the constants generated by Meson in config.h to Vala.
[CCode (cheader_filename = "config.h")]
namespace Config {
    [CCode (cname = "CONFIG_APP_ID")]
    public const string APP_ID;
    [CCode (cname = "CONFIG_GETTEXT_PACKAGE")]
    public const string GETTEXT_PACKAGE;
    [CCode (cname = "CONFIG_LOCALEDIR")]
    public const string LOCALEDIR;
    [CCode (cname = "CONFIG_VERSION")]
    public const string VERSION;
}
